version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: romeo_container
    environment:
      - POSTGRES_PASSWORD=1111
      - POSTGRES_USER=romeo_postgres
      - POSTGRES_DB=romeo_db
    ports:
      - "1234:5432"
